# -*- coding: utf-8 -*-
"""CEASAR CIPHER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GALuY1B6s1dCd73RLqvc8GJu76kCEEFv
"""

def encrypt(text,s): 
  result = ""
   # transverse the plain text
 # print(len(text))
  for i in range(len(text)):
      char = text[i]
     # print(char)
      # Encrypt uppercase characters in plain text
      
      if (char.isupper()):
        result += chr((ord(char) + s-65) % 26 + 65)
        #print(result)
      # Encrypt lowercase characters in plain text
      elif(char.islower()):
        result += chr((ord(char) + s - 97) % 26 + 97)
        #print(result)
      else:
        result += char
  return result
#check the above function
text = "CEASER CIPHER DEMO"
s = 4

def decrypt(text,s):
  res = ""
  for i in range(len(text)):
    char = text[i]
    if(char.isupper()):
      res += chr((ord(char) - s - 65 +26 )%26 + 65)
    elif(char.islower()):
      res += chr((ord(char) - s - 97 -26 )%26 +97)
    else:
      res += char
  return res
print("Plain Text : " + text)
print ("Shift pattern : " + str(s))
print ("Cipher: " + encrypt(text,s))
print( " Plain Text: "+ decrypt(encrypt(text,s),s))

## CIPHER text only
def attack(cipher):
  for j in range(26):
      print(j,decrypt(cipher,j))
cipher = "GIEWIV"
attack(cipher)

## known plain text 
def attack(cipher):
  j=0
  for j in range(26):
      t = j,decrypt(cipher,j)
      if t == plain:
        return j
    #print("Not a ceasar cipher encrypted text")
plain = "CEASAR"
cipher = "GIEWIV"
j = attack(cipher)
print("Key = ",j)

